[generate:profile] fix passing profile or machine name on the command line (#3036)
When passing profile or machine-name on the command line like that:

  drupal generate:profile --profile=PROFILE --machine-name=MACHINE_NAME

drupal console gives an error:

Error: Call to undefined method Drupal\Console\Command\Generate\ProfileCommand::validateModuleName() in Drupal\Console\Command\Generate\ProfileCommand->interact() (line 234 of .../vendor/drupal/console/src/Command/Generate/ProfileCommand.php).

After fixing this another similar error shows up:

Error: Call to undefined method Drupal\Console\Command\Generate\ProfileCommand::validateModule() in Drupal\Console\Command\Generate\ProfileCommand->interact() (line 253 of .../vendor/drupal/console/src/Command/Generate/ProfileCommand.php).

Fix both so that the command line from above works again.

Closes #3035